{{- if .Values.serviceMesh.istio.exists }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: {{.Release.Namespace}}
  name: allow-health-check-request
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/health_check"]
{{- end}}
