{{- if .Values.serviceMesh.istio.exists }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Release.Name}}-sembed-vs
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - {{ .Values.serviceMesh.istio.host }}
  gateways:
    - {{.Release.Namespace}}/{{.Release.Name}}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{.Values.service.port | int }}
        host: {{.Release.Name}}.{{.Release.Namespace}}.svc.cluster.local
{{- end}}
