{{- if and .Values.serviceMesh.istio.exists .Values.serviceMesh.istio.jwtAuth.enable }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-jwt-sembed
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: {{ .Values.serviceMesh.istio.jwtAuth.requestPrincipals }}
{{- end}}

