apiVersion: v1
kind: Service
metadata:
  name: {{ include "sembed.fullname" . }}
  labels:
    {{- include "sembed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.service.application_port | int }}
      protocol: TCP
      name: http
  selector:
    {{- include "sembed.selectorLabels" . | nindent 4 }}
